# Generated by Django 4.2.16 on 2025-04-07 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('spotify_id', models.CharField(max_length=255)),
                ('mood_tags', models.CharField(max_length=255)),
                ('artist_follower_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
                ('subscription_tier', models.CharField(max_length=255)),
                ('social_credit', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('preferred_genres', models.CharField(max_length=255)),
                ('preferred_moods', models.CharField(max_length=255)),
                ('favorite_artists', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.users')),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('time_of_creation', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.users')),
            ],
        ),
        migrations.CreateModel(
            name='Contextinfo',
            fields=[
                ('pid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('weather', models.CharField(max_length=255)),
                ('time_of_day', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.users')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_order', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.playlists')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.songs')),
            ],
            options={
                'unique_together': {('playlist', 'song', 'song_order')},
            },
        ),
    ]
